version: '2'

services:
    zookeeper1:
        image: zookeeper:3.4
        restart: always
        container_name: zookeeper1
        hostname: zookeeper1
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
        volumes:
            - /opt/log/zookeeper1:/datalog
            - /opt/run/zookeeper1:/data

    zookeeper2:
        image: zookeeper:3.4
        restart: always
        container_name: zookeeper2
        hostname: zookeeper2
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
        volumes:
            - /opt/log/zookeeper2:/datalog
            - /opt/run/zookeeper2:/data

    zookeeper3:
        image: zookeeper:3.4
        restart: always
        container_name: zookeeper3
        hostname: zookeeper3
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
        volumes:
            - /opt/log/zookeeper3:/datalog
            - /opt/run/zookeeper3:/data
